<select title="selectable options" id="find_dealer" width="30%" class="filterState" value="">
        <option attr="" id="find_dealer_" value=""> </option>
                    <option attr="AL" value="Alabama">Alabama</option>
                    <option attr="AK" value="Alaska">Alaska</option>
                    <option attr="AZ" value="Arizona">Arizona</option>
                    <option attr="AR" value="Arkansas">Arkansas</option>
                    <option attr="CA" value="California">California</option>
                    <option attr="CO" value="Colorado">Colorado</option>
                    <option attr="CT" value="Connecticut">Connecticut</option>
                    <option attr="DE" value="Delaware">Delaware</option>
                    <option attr="DC" value="District of Columbia">District of Columbia</option>
                    <option attr="FL" value="Florida">Florida</option>
                    <option attr="GA" value="Georgia">Georgia</option>
                    <option attr="HI" value="Hawaii">Hawaii</option>
                    <option attr="ID" value="Idaho">Idaho</option>
                    <option attr="IL" value="Illinois">Illinois</option>
                    <option attr="IN" value="Indiana">Indiana</option>
                    <option attr="IA" value="Iowa">Iowa</option>
                    <option attr="KS" value="Kansas">Kansas</option>
                    <option attr="KY" value="Kentucky">Kentucky</option>
                    <option attr="LA" value="Louisiana">Louisiana</option>
                    <option attr="ME" value="Maine">Maine</option>
                    <option attr="MD" value="Maryland">Maryland</option>
                    <option attr="MA" value="Massachusetts">Massachusetts</option>
                    <option attr="MI" value="Michigan">Michigan</option>
                    <option attr="MN" value="Minnesota">Minnesota</option>
                    <option attr="MS" value="Mississippi">Mississippi</option>
                    <option attr="MO" value="Missouri">Missouri</option>
                    <option attr="MT" value="Montana">Montana</option>
                    <option attr="NE" value="Nebraska">Nebraska</option>
                    <option attr="NV" value="Nevada">Nevada</option>
                    <option attr="NH" value="New Hampshire">New Hampshire</option>
                    <option attr="NJ" value="New Jersey">New Jersey</option>
                    <option attr="NM" value="New Mexico">New Mexico</option>
                    <option attr="NY" value="New York">New York</option>
                    <option attr="NC" value="North Carolina">North Carolina</option>
                    <option attr="ND" value="North Dakota">North Dakota</option>
                    <option attr="OH" value="Ohio">Ohio</option>
                    <option attr="OK" value="Oklahoma">Oklahoma</option>
                    <option attr="OR" value="Oregon">Oregon</option>
                    <option attr="PA" value="Pennsylvania">Pennsylvania</option>
                    <option attr="RI" value="Rhode Island">Rhode Island</option>
                    <option attr="SC" value="South Carolina">South Carolina</option>
                    <option attr="SD" value="South Dakota">South Dakota</option>
                    <option attr="TN" value="Tennessee">Tennessee</option>
                    <option attr="TX" value="Texas">Texas</option>
                    <option attr="UT" value="Utah">Utah</option>
                    <option attr="VT" value="Vermont">Vermont</option>
                    <option attr="VA" value="Virginia">Virginia</option>
                    <option attr="WA" value="Washington">Washington</option>
                    <option attr="WV" value="West Virginia">West Virginia</option>
                    <option attr="WI" value="Wisconsin">Wisconsin</option>
                    <option attr="WY" value="Wyoming">Wyoming</option>
                    <option attr="AB" value="Alberta">Alberta</option>
                    <option attr="BC" value="British Columbia">British Columbia</option>
                    <option attr="MB" value="Manitoba">Manitoba</option>
                    <option attr="ON" value="Ontario">Ontario</option>
                    <option attr="QC" value="Quebec">Quebec</option>
                    <option attr="SK" value="Saskatchewan">Saskatchewan</option>
                    <option attr="MX" value="Mexico">Mexico</option>
                    <option attr="CARIB" value="Caribbean">Caribbean</option>
                </select>
